<a href="https://colab.research.google.com/github/felipemanfrin/NLP/blob/master/TENSORFLOOOOU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow


In [ ]:
import tensorflow as tf
print (tf.__version__)

2.3.0


In [ ]:
!pip install keras


In [ ]:
!pip install sklearn

In [ ]:
!pip install pandas


In [ ]:
!pip install numpy


In [1]:
import numpy as np
from sklearn.datasets import load_iris


In [2]:
iris = load_iris()

In [3]:
type(iris)

sklearn.utils.Bunch

In [4]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [5]:
X = iris.data

In [6]:
y = iris.target

In [7]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
from keras.utils import to_categorical

In [9]:
y = to_categorical(y)

In [10]:
y.shape

(150, 3)

In [11]:
#y

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [14]:
#y_train

In [15]:
from sklearn.preprocessing import MinMaxScaler

In [16]:
#np.array([5, 10, 15, 20])/20

In [17]:
scaler_object = MinMaxScaler()

In [18]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [19]:
scaled_X_train = scaler_object.transform(X_train)

In [20]:
scaled_X_test = scaler_object.transform(X_test)

In [21]:
scaled_X_train

array([[0.41176471, 0.40909091, 0.55357143, 0.5       ],
       [0.97058824, 0.45454545, 0.98214286, 0.83333333],
       [0.38235294, 0.45454545, 0.60714286, 0.58333333],
       [0.23529412, 0.68181818, 0.05357143, 0.04166667],
       [1.        , 0.36363636, 1.        , 0.79166667],
       [0.44117647, 0.31818182, 0.53571429, 0.375     ],
       [0.26470588, 0.63636364, 0.05357143, 0.04166667],
       [0.20588235, 0.68181818, 0.03571429, 0.08333333],
       [0.23529412, 0.81818182, 0.14285714, 0.125     ],
       [0.20588235, 0.        , 0.42857143, 0.375     ],
       [0.58823529, 0.31818182, 0.67857143, 0.70833333],
       [0.14705882, 0.63636364, 0.14285714, 0.04166667],
       [0.20588235, 0.45454545, 0.08928571, 0.04166667],
       [0.23529412, 0.59090909, 0.10714286, 0.16666667],
       [0.38235294, 0.31818182, 0.55357143, 0.5       ],
       [0.23529412, 0.63636364, 0.07142857, 0.04166667],
       [0.41176471, 0.45454545, 0.55357143, 0.45833333],
       [1.        , 0.81818182,

In [22]:
from keras.models import Sequential
from keras.layers import  Dense

In [23]:
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [24]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 8)                 40        
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [25]:
model.fit(scaled_X_train, y_train, epochs=150, verbose=2)

Epoch 1/150
4/4 - 0s - loss: 1.1866 - accuracy: 0.3100
Epoch 2/150
4/4 - 0s - loss: 1.1749 - accuracy: 0.3100
Epoch 3/150
4/4 - 0s - loss: 1.1653 - accuracy: 0.3100
Epoch 4/150
4/4 - 0s - loss: 1.1562 - accuracy: 0.3100
Epoch 5/150
4/4 - 0s - loss: 1.1479 - accuracy: 0.3000
Epoch 6/150
4/4 - 0s - loss: 1.1393 - accuracy: 0.3000
Epoch 7/150
4/4 - 0s - loss: 1.1323 - accuracy: 0.3000
Epoch 8/150
4/4 - 0s - loss: 1.1245 - accuracy: 0.3000
Epoch 9/150
4/4 - 0s - loss: 1.1180 - accuracy: 0.3000
Epoch 10/150
4/4 - 0s - loss: 1.1121 - accuracy: 0.3000
Epoch 11/150
4/4 - 0s - loss: 1.1060 - accuracy: 0.3000
Epoch 12/150
4/4 - 0s - loss: 1.1003 - accuracy: 0.3000
Epoch 13/150
4/4 - 0s - loss: 1.0946 - accuracy: 0.3000
Epoch 14/150
4/4 - 0s - loss: 1.0890 - accuracy: 0.3000
Epoch 15/150
4/4 - 0s - loss: 1.0835 - accuracy: 0.3000
Epoch 16/150
4/4 - 0s - loss: 1.0782 - accuracy: 0.3200
Epoch 17/150
4/4 - 0s - loss: 1.0732 - accuracy: 0.3400
Epoch 18/150
4/4 - 0s - loss: 1.0685 - accuracy: 0.3600
E

In [30]:
np.argmax(model.predict(scaled_X_test), axis=-1)

array([2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 2, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 2, 2, 2, 0,
       0, 2, 2, 2, 2, 2])

In [31]:
predictions = model.predict_classes(scaled_X_test)

In [33]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [34]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [35]:
confusion_matrix(y_test.argmax(axis=1),predictions)

array([[19,  0,  0],
       [ 0,  0, 15],
       [ 0,  0, 16]])

In [36]:
print(classification_report(y_test.argmax(axis=1), predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.00      0.00      0.00        15
           2       0.52      1.00      0.68        16

    accuracy                           0.70        50
   macro avg       0.51      0.67      0.56        50
weighted avg       0.55      0.70      0.60        50



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [37]:
accuracy_score(y_test.argmax(axis=1), predictions)

0.7

In [38]:
model.save('myfirstmodel.h5')

In [39]:
from keras.models import load_model

In [41]:
new_model = load_model('myfirstmodel.h5')

In [42]:
new_model.predict_classes(scaled_X_test)

array([2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 2, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 2, 2, 2, 0,
       0, 2, 2, 2, 2, 2])

In [ ]:
dfgsdfgdsfg